# Lab 03. Intruduction to pandas

Pandas jest biblioteką języka Python, która pozwala na przetwarzanie tabelarycznych zbiorów danych różnych typów (np. csv, excel, json). Możemy te dane wyświetlać, filtrować, sortować, grupować i wykonywać na nich przeróżne przekształcenia i obliczenia. 

Podstawowym komponentem biblioteki pandas są ramki danych (pandas DataFrame) oraz serie danych (pandas Series), z których ramka danych się składa.

> Dokumentacja: https://pandas.pydata.org/docs/

Biblioteka pandas jest bardzo rozbudowana, więc zaprezentowane zostaną tylko wybrane jej elementy, aby zaprezentować jej ogólne możliwości.

## 0. Instllation and import of pandas library

Installing packages with `pip` tool is quite easy if we know the name of the desired package.
Running `pip` is not a Python command, but a operating system command so we need to run it by providing an exclamation mark before the command. That will run the command using system shell (tool where you can communicate with the operating system via text commands in thhe terminal).

In [ ]:
!pip install pandas

In [2]:
# no import, so we can use it in this notebook
import pandas as pd

## 1. Loading the data

Biblioteka pandas obsługuje wiele formatów danych, ale i sposobów ich wczytywania (np. bezpośrednio z Internetu poprzez protokół HTTP). 

Let's create a simple pandas DataFrame from a dictionary.

In [6]:
my_data = {
    'name': ['Bob','Julia','Greg','John','Wolfgang','Maciek','Kate'],
    'score': [12, 10, 13, 9, 12, 14, 11]
}

# we are creating pandas dataframe from dictionary data, where each key becomes a column in the frame
df_1 = pd.DataFrame(my_data)

In [5]:
df_1

       name  score
0       Bob     12
1     Julia     10
2      Greg     13
3      John      9
4  Wolfgang     12
5    Maciek     14
6      Kate     11

As you see there are three columns where the first one was created automatically and is called an `index`.

Let's write the data to a file, and then load them once again.

In [10]:
# pandas allows us to save it's data to a file with different formats
# let's choose something simple and very popular - CSV (comma separated values)
df_1.to_csv('my_data.csv')

Now you can see a file `my_data.csv` within the same folder as the notebook. You can also view it directly within web browser. You probably noticed that the column `index` is also present, which is not necessary somethimes. We can avoid this behaviour by providing a flag `index` set to `False` to do not save the index into a file. Let's try again overwriting the file.

In [11]:
df_1.to_csv('my_data.csv', index=False)

Now the `index` column is gone. We can also do the same with the column headers, but this feature is rather a good default to store then within a file. We can set the `header=False` flag though to disable column header from being written into a file.

**Now lets read the data from a file.**

Let's load the data back again to practice.

In [12]:
df_2 = pd.read_csv('my_data.csv')
df_2

       name  score
0       Bob     12
1     Julia     10
2      Greg     13
3      John      9
4  Wolfgang     12
5    Maciek     14
6      Kate     11

**Let's get the data directly from the Internet**

In [ ]:
# we get the URL for the data from my GitHub, but as a direct link to the data

df_3 = pd.read_csv('zamowienia.csv'