# Lab 03. Introduction to pandas

Pandas is a Python library that allows you to process tabular datasets of various types (e.g., CSV, Excel, JSON). You can display, filter, sort, and group this data, as well as perform various transformations and calculations on it.

The core components of the pandas library are DataFrames and Series, of which a DataFrame is composed.

> **Documentation**: https://pandas.pydata.org/docs/

The pandas library is very extensive, so only selected elements will be presented to demonstrate its general capabilities.

## 0. Installation and import of pandas library

Installing packages with `pip` tool is quite easy if we know the name of the desired package.
Running `pip` is not a Python command, but a operating system command so we need to run it by providing an exclamation mark before the command. That will run the command using system shell (tool where you can communicate with the operating system via text commands in thhe terminal).

In [ ]:
!pip install pandas

In [2]:
# no import, so we can use it in this notebook
import pandas as pd

## 1. Loading the data

The pandas library supports many data formats, as well as various methods for loading them (e.g., directly from the Internet via the HTTP protocol).
 

Let's create a simple pandas DataFrame from a dictionary.

In [6]:
my_data = {
    'name': ['Bob','Julia','Greg','John','Wolfgang','Maciek','Kate'],
    'score': [12, 10, 13, 9, 12, 14, 11]
}

# we are creating pandas dataframe from dictionary data, where each key becomes a column in the frame
df_1 = pd.DataFrame(my_data)

In [5]:
df_1

       name  score
0       Bob     12
1     Julia     10
2      Greg     13
3      John      9
4  Wolfgang     12
5    Maciek     14
6      Kate     11

As you see there are three columns where the first one was created automatically and is called an `index`.

Let's write the data to a file, and then load them once again.

In [10]:
# pandas allows us to save it's data to a file with different formats
# let's choose something simple and very popular - CSV (comma separated values)
df_1.to_csv('my_data.csv')

Now you can see a file `my_data.csv` within the same folder as the notebook. You can also view it directly within web browser. You probably noticed that the column `index` is also present, which is not necessary somethimes. We can avoid this behaviour by providing a flag `index` set to `False` to do not save the index into a file. Let's try again overwriting the file.

In [11]:
df_1.to_csv('my_data.csv', index=False)

Now the `index` column is gone. We can also do the same with the column headers, but this feature is rather a good default to store then within a file. We can set the `header=False` flag though to disable column header from being written into a file.

**Now lets read the data from a file.**

Let's load the data back again to practice.

In [12]:
df_2 = pd.read_csv('my_data.csv')
df_2

       name  score
0       Bob     12
1     Julia     10
2      Greg     13
3      John      9
4  Wolfgang     12
5    Maciek     14
6      Kate     11

**Let's get the data directly from the Internet**

In [18]:
# we get the URL for the data from my GitHub, but as a direct link to the data
url = 'https://raw.githubusercontent.com/kropiak/__biostatistics_it_2026/refs/heads/main/lab_03/orders.csv'

df_3 = pd.read_csv(url)
# get only the first 10 rows
df_3.head(10)

  Country;Employee;Order_date;Order_id;Order_value
0          Polska;Kowalski;2003-07-16;10248;440.00
1         Polska;Sowiński;2003-07-10;10249;1863.40
2          Niemcy;Peacock;2003-07-12;10250;1552.60
3         Niemcy;Leverling;2003-07-15;10251;654.06
4          Niemcy;Peacock;2003-07-11;10252;3597.90
5        Niemcy;Leverling;2003-07-16;10253;1444.80
6          Polska;Kowalski;2003-07-23;10254;556.62
7            Polska;Dudek;2003-07-15;10255;2490.50
8         Niemcy;Leverling;2003-07-17;10256;517.80
9          Niemcy;Peacock;2003-07-22;10257;1119.90

In [19]:
# something's wrong with the data - the separator is ; not the ','  which is the default one for pandas
# we can provide a separator (sep parameter) in the read_csv function

df_3 = pd.read_csv(url, sep=';')
# get only the first 10 rows
df_3.head(10)

  Country   Employee  Order_date  Order_id  Order_value
0  Polska   Kowalski  2003-07-16     10248       440.00
1  Polska   Sowiński  2003-07-10     10249      1863.40
2  Niemcy    Peacock  2003-07-12     10250      1552.60
3  Niemcy  Leverling  2003-07-15     10251       654.06
4  Niemcy    Peacock  2003-07-11     10252      3597.90
5  Niemcy  Leverling  2003-07-16     10253      1444.80
6  Polska   Kowalski  2003-07-23     10254       556.62
7  Polska      Dudek  2003-07-15     10255      2490.50
8  Niemcy  Leverling  2003-07-17     10256       517.80
9  Niemcy    Peacock  2003-07-22     10257      1119.90

## 2. Basic information about the data in pandas DataFrame

We can get some information about the type of the data, the number of rows etc.

Two basic functions are `info()` and `describe()` we can run directly on a whole DataFrame.

In [20]:
df_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      799 non-null    str
 1   Employee     799 non-null    str
 2   Order_date   799 non-null    str
 3   Order_id     799 non-null    int64
 4   Order_value  799 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 31.3 KB

We can observer data type for each column (like for the column in excel) which is very important in the sense of future possible operations on the data. Data type could be changed but preserving validity rules for a specific type (non digit values can not be converted into numeric type).

In [21]:
df_3.describe()

           Order_id   Order_value
count    799.000000    799.000000
mean   10647.175219   1537.330914
std      231.091915   1860.590758
min    10248.000000     12.500000
25%    10447.500000    467.075000
50%    10647.000000    956.670000
75%    10846.500000   1891.375000
max    11057.000000  16387.500000

In [22]:
# we can also get only the data types by running
df_3.dtypes

Country            str
Employee           str
Order_date         str
Order_id         int64
Order_value    float64
dtype: object

## 3. Selecting data from pandas DataFrame

We can select any subset of data from the original DataFrame and there are many different ways to achieve the goal.

### 3.1 Selecting by column/index oraz indices

In [26]:
# single column - returns pandas Series
df_3['Country']

0      Polska
1      Polska
2      Niemcy
3      Niemcy
4      Niemcy
        ...
794    Polska
795    Niemcy
796    Niemcy
797    Niemcy
798    Niemcy
Name: Country, Length: 799, dtype: str

In [27]:
# many columns - returns pandas DataFrame
df_3[['Country','Employee']]

    Country   Employee
0    Polska   Kowalski
1    Polska   Sowiński
2    Niemcy    Peacock
3    Niemcy  Leverling
4    Niemcy    Peacock
..      ...        ...
794  Polska       King
795  Niemcy  Leverling
796  Niemcy     Fuller
797  Niemcy   Callahan
798  Niemcy  Leverling

[799 rows x 2 columns]

In [30]:
# selecting may be done by providing names of columns or values in index column (for row selection)
#  or by providing indices of those columns or rows

# loc method (index name, [columns])
# one row
df_3.loc[4, ['Employee']]

Employee    Peacock
Name: 4, dtype: str

In [31]:
# loc method (index name, [columns])
# rows with values from 0 to 5 and all columns (:) - slicing
df_3.loc[:5, :]

  Country   Employee  Order_date  Order_id  Order_value
0  Polska   Kowalski  2003-07-16     10248       440.00
1  Polska   Sowiński  2003-07-10     10249      1863.40
2  Niemcy    Peacock  2003-07-12     10250      1552.60
3  Niemcy  Leverling  2003-07-15     10251       654.06
4  Niemcy    Peacock  2003-07-11     10252      3597.90
5  Niemcy  Leverling  2003-07-16     10253      1444.80

In [32]:
# iloc uses indices instead of names

# slice - indexes 0,1,2,3,4 (stop = 5 is excluded)
df_3.iloc[:5, :]

  Country   Employee  Order_date  Order_id  Order_value
0  Polska   Kowalski  2003-07-16     10248       440.00
1  Polska   Sowiński  2003-07-10     10249      1863.40
2  Niemcy    Peacock  2003-07-12     10250      1552.60
3  Niemcy  Leverling  2003-07-15     10251       654.06
4  Niemcy    Peacock  2003-07-11     10252      3597.90

### 3.2 Filtering data by condition

Filtering data is about creating a logical condition which is then applied on each given item in the data set oraz a slice from it.

This is actually a two step process. Creating a condition produces a `boolean map` (vector/matrix/tensor) with `True` and `False` values. Then this map in applied to real data and those which are at the positions where map contains `True` value are being selected, and those on positions with `False` value are being filtered out.

Let's try it out on an example.

In [34]:
order_value_sample = df_3['Order_value'][:5]
order_value_sample

0     440.00
1    1863.40
2    1552.60
3     654.06
4    3597.90
Name: Order_value, dtype: float64

In [35]:
# examplary map, created from a condition, separated from the data
order_value_sample > 1000

0    False
1     True
2     True
3    False
4     True
Name: Order_value, dtype: bool

In [36]:
# now, we apply that map (filter) on the data
order_value_sample[order_value_sample > 1000]

1    1863.4
2    1552.6
4    3597.9
Name: Order_value, dtype: float64

In [33]:
# let's try it on sample with 2 columns
data_sample = df_3.loc[:4, ['Employee', 'Order_value']]
data_sample

    Employee  Order_value
0   Kowalski       440.00
1   Sowiński      1863.40
2    Peacock      1552.60
3  Leverling       654.06
4    Peacock      3597.90

In [40]:
# the same filter, but on DataFrame, this will show whole rows, where in the given column the condition is met
# map is the same
print(data_sample['Order_value'] > 1000)

# but applied to rows
data_sample[data_sample['Order_value'] > 1000]

0    False
1     True
2     True
3    False
4     True
Name: Order_value, dtype: bool

   Employee  Order_value
1  Sowiński       1863.4
2   Peacock       1552.6
4   Peacock       3597.9

In [44]:
# we can apply multiple conditions like filtering any table (in excel for example)
# [(condition) & (condition)] - sum of conditions (condition AND condition)
# [(condition) | (condition)] - alternative conditions (condition OR condition)
df_3[(df_3['Order_value'] > 5000) & (df_3['Country'] == 'Polska')]

    Country  Employee  Order_date  Order_id  Order_value
76   Polska     Dudek  2003-10-10     10324      5275.71
105  Polska      King  2003-11-25     10353      8593.28
124  Polska  Kowalski  2003-12-09     10372      9210.90
176  Polska      King  2004-01-27     10424      9194.56
359  Polska  Kowalski  2004-07-25     10607      6475.40
385  Polska      King  2004-08-18     10633      5510.59
430  Polska      King  2004-10-16     10678      5256.50
641  Polska     Dudek  2005-02-23     10889     11380.00
645  Polska     Dudek  2005-02-20     10893      5502.11
768  Polska     Dudek  2005-04-20     11017      6750.00
779  Polska      King  2005-04-27     11030     12615.05

One can also use functions to work with strings like in the examles below.

In [54]:
# str.startswith - looks for a string at the beginning of a compared string
df_3[df_3['Order_date'].str.startswith('2004')]

    Country  Employee  Order_date  Order_id  Order_value
132  Niemcy  Callahan  2004-01-16     10380      1313.82
144  Niemcy    Fuller  2004-01-01     10392      1440.00
145  Niemcy   Davolio  2004-01-03     10393      2556.95
146  Niemcy   Davolio  2004-01-03     10394       442.00
147  Polska  Sowiński  2004-01-03     10395      2122.92
..      ...       ...         ...       ...          ...
539  Niemcy    Fuller  2004-12-26     10787      2622.76
541  Niemcy   Davolio  2004-12-31     10789      3687.00
542  Polska  Sowiński  2004-12-26     10790       722.50
544  Niemcy   Davolio  2004-12-31     10792       399.85
553  Niemcy   Peacock  2004-12-31     10801      3026.85

[399 rows x 5 columns]

In [57]:
# in - it is a contains relation - answers a question if an object is in collection/squence
# and as we know Python str type is a sequence - we ca check if a string is within a strind
'Alice' in 'Alice in wonderland'

True

In [ ]:
# but in pandas array (numpy is being used as a data library for it) we need to do it in another way
# we will use a str.contains() function

In [61]:
df_3[df_3['Employee'].str.contains('ski')]

    Country  Employee  Order_date  Order_id  Order_value
0    Polska  Kowalski  2003-07-16     10248       440.00
1    Polska  Sowiński  2003-07-10     10249      1863.40
6    Polska  Kowalski  2003-07-23     10254       556.62
16   Polska  Sowiński  2003-08-23     10264       695.62
21   Polska  Kowalski  2003-08-09     10269       642.20
..      ...       ...         ...       ...          ...
725  Polska  Sowiński  2005-03-27     10973       291.55
751  Polska  Sowiński  2005-04-10     10999      1197.95
774  Polska  Sowiński  2005-04-24     11025       270.00
780  Polska  Sowiński  2005-04-24     11031      2393.50
790  Polska  Kowalski  2005-04-29     11043       210.00

[107 rows x 5 columns]

## 4. Calculations based on data from the dataframes

Let's assume that we are interested in answering a few questions:
* What is the sum of orders for `Polska`?
* How many orders there are for `Niemcy`?
* What is the average value for an order?

In [45]:
# first we need to select proper data
q_1 = df_3[df_3['Country'] == 'Polska']
q_1

    Country  Employee  Order_date  Order_id  Order_value
0    Polska  Kowalski  2003-07-16     10248       440.00
1    Polska  Sowiński  2003-07-10     10249      1863.40
6    Polska  Kowalski  2003-07-23     10254       556.62
7    Polska     Dudek  2003-07-15     10255      2490.50
15   Polska     Dudek  2003-07-31     10263      1873.80
..      ...       ...         ...       ...          ...
782  Polska      King  2005-04-23     11033      3232.80
786  Polska      King  2005-04-27     11037        60.00
790  Polska  Kowalski  2005-04-29     11043       210.00
793  Polska      King  2005-05-01     11047       817.87
794  Polska      King  2005-04-30     11048       525.00

[215 rows x 5 columns]

In [48]:
# now we can apply a function on a given data or a subset
# this result is not what we were thinking of
q_1.sum()

# now it looks better
q_1['Order_value'].sum()

np.float64(333330.91)

In [50]:
# we could aplly all of the steps in one line - like a chain of functions executed from left to right (more or less)
df_3[df_3['Country'] == 'Polska']['Order_value'].sum()

np.float64(333330.91)

To know the functions, their parameters and values being returned we need to know the API (Application Programming Interface) of pandas DataFrame.

> Api dosc for pandas: https://pandas.pydata.org/docs/reference/index.html#api

## 5. Exercises

**Exercise 1**

Find the answer for second question in the subsection 4.

**Exercise 2**

Find the answer for third question in the subsection 4.

**Exercise 3**

What is the total sum of order values?

**Exercise 4**

What is the proportion of order values for each country?

**Exercise 5**

What is the number of orders for each year?*

\* This requires to use some string comparison functions as the columns with the date is of `str` type for now.